In [10]:
#Data analysis:
#Statistics is very important in analysis because it gives out useful inferences from data .
#Statistical sinificance test:test which is used to make assumptions about data distributions.


In [11]:
#Normal distribution:
#Example:Gaussian distribution/bell curve/Normal distributions.
#Normal distribution are symmetric about their mean.
#we deal with 2 parameters : mean,standard deviation
#Y = { 1/sqrt(2πσ2)} * e-(x - μ)2/2σ2

In [12]:
#t-test(statistical significance test):
#t-test is used to accept/reject a null hypothesis which is basically we try to  disapprove a statement by running a test.
#t test is specified by a number that helps us to reject/accept a null hypothesis.

In [13]:
#welch's two sample test:
#we compute a t statistic using equation:
#t=(mean1-mean2)/sqrt[(variance1/size1)+(variance2/size2)]
#we set p critical ,so if we p<pcrticial then we reject the null hypothesis 
                                 #else accpet the null hypothesis.
    

In [ ]:
#Machine Learning: 
#Branch of AI that uses existing data to predict future
#stats vs machine learning : stats is basically focused on analysing existing data and drawing conclusions.
#machine learning is bascially making predicting. 
#types of ML:
#Supervised learning: Basically we train the model using  input-output .and then we use the model for prediciting.
#classification,regression.
#categrozing mails to spam.
#unsupervised learing : we dont have structured data.instead we have data point and we put togetgehr similar data point and try to undertsand the structure.

# Data analysis::

#Data Analysis process::

In [ ]:
#Data analyst usually uses data to answer questions.

In [ ]:
#Process:
#step1: we always start with Question phase--what we need from analysing of data.
#step2: wrangling phase--data acquisition + data cleaning.
#step3: Data exploration phase--usually you get familiar with data i.e you identify patterns/findings etc.
#step4: drawing conclusions/making predictions -- usually you make predictions from above data--involoves statistics and ML.
#step5: Communication phase---you need to communicate your findings/predictions to your team and answer the ques asked in 1 phase--via blog post,email,ppt,verbal.

#you might sometimes acquire data first then wrangle.
#you might also want to switch between wrangle and explore phase.

#Data wrangling phase::

In [ ]:
#you might get your data from various sources :
#Downloading data
#Acessing an  API
#Scrapping a web page
#combine data  from different sources

In [ ]:
#CSV Data format:
#usually our data is in CSV Format(Comma separated value)--easy with code unlike excel.
#Each of csv is represented as list of rows---
#option1: each row is list--csv=[['a1','a2'],
#                               ['b1','b2']]
#option2: each row is a dictionary--so each columnname is key and fields are values--overall csv is list of dictionaries
# csv=[{'columnname1':'a1' ,'columnname2':'a2'}
#       {'columnname1':'b1','columnname2':'b2'}]
#preferable when we have header rows.


In [17]:
#In pyhton,data can be raed directly using python libraries--
import pandas as pd
enrollment_df=pd.read_csv("enrollments.csv")
enrollment_df.head()

account_key    status   join_date cancel_date  days_to_cancel  is_udacity  \
0          448  canceled  2014-11-10  2015-01-14            65.0        True   
1          448  canceled  2014-11-05  2014-11-10             5.0        True   
2          448  canceled  2015-01-27  2015-01-27             0.0        True   
3          448  canceled  2014-11-10  2014-11-10             0.0        True   
4          448   current  2015-03-10         NaN             NaN        True   

   is_canceled  
0         True  
1         True  
2         True  
3         True  
4        False

In [18]:
#set join_date as Date Time type:
enrollment_df['join_date']=pd.to_datetime(enrollment_df['join_date']).dt.strftime('%d-%m-%y')
enrollment_df['account_key'] = pd.to_numeric(enrollment_df['account_key'])
enrollment_df

account_key    status join_date cancel_date  days_to_cancel  is_udacity  \
0             448  canceled  10-11-14  2015-01-14            65.0        True   
1             448  canceled  05-11-14  2014-11-10             5.0        True   
2             448  canceled  27-01-15  2015-01-27             0.0        True   
3             448  canceled  10-11-14  2014-11-10             0.0        True   
4             448   current  10-03-15         NaN             NaN        True   
...           ...       ...       ...         ...             ...         ...   
1635         1176   current  12-08-15         NaN             NaN       False   
1636         1110   current  13-08-15         NaN             NaN       False   
1637         1116  canceled  15-08-15  2015-08-18             3.0       False   
1638          874   current  22-08-15         NaN             NaN       False   
1639          686   current  23-08-15         NaN             NaN       False   

      is_canceled  
0            True  
1            True  
2            True  
3            True  
4           False  
...           ...  
1635        False  
1636        False  
1637         True  
1638        False  
1639        False  

[1640 rows x 7 columns]

In [19]:
#find total number of rows:
print(len(enrollment_df))
#find unique enrollments: ---find unique account_key and then take count.
print(len(enrollment_df['account_key'].unique()))

1640
1302


In [20]:
#find accounts where is_udacity==true::
new_df=enrollment_df[enrollment_df["is_udacity"] == True]
new_df.head(2)

account_key    status join_date cancel_date  days_to_cancel  is_udacity  \
0          448  canceled  10-11-14  2015-01-14            65.0        True   
1          448  canceled  05-11-14  2014-11-10             5.0        True   

   is_canceled  
0         True  
1         True

#Numpy array:

In [21]:
#Numpy array:
#works same as array indexing--arr[0]
#works on slicing as well--arr[1:3]--will givve elements at 1 and 2 position.
#you can use loops--for x in arr.
#each elemnet should be of same type.
#numpy arrays can be multidimensional.

import numpy as np
# First 20 countries with employment data
countries = np.array([
    'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
    'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
    'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
    'Belize', 'Benin', 'Bhutan', 'Bolivia',
    'Bosnia and Herzegovina'])

# Employment data in 2007 for those 20 countries
employment = np.array([
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076])

# Accessing elements
if True:
    print(countries[0])
    print(countries[3])

# Slicing
if True:
    print(countries[0:3])
    print(countries[:3])
    print(countries[17:])
    print(countries[:])

# Element types
if True:
    print(countries.dtype)
    print(employment.dtype)
    print(np.array([0, 1, 2, 3]).dtype)
    print(np.array([1.0, 1.5, 2.0, 2.5]).dtype)
    print(np.array([True, False, True]).dtype)
    print(np.array(['AL', 'AK', 'AZ', 'AR', 'CA']).dtype)



Afghanistan
Angola
['Afghanistan' 'Albania' 'Algeria']
['Afghanistan' 'Albania' 'Algeria']
['Bhutan' 'Bolivia' 'Bosnia and Herzegovina']
['Afghanistan' 'Albania' 'Algeria' 'Angola' 'Argentina' 'Armenia'
 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain' 'Bangladesh'
 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bhutan' 'Bolivia'
 'Bosnia and Herzegovina']
<U22
float64
int32
float64
bool
<U2


In [22]:
# Looping
if True:
    for country in countries:
        print('Examining country {}'.format(country))

    for i in range(len(countries)):
        country = countries[i]
        country_employment = employment[i]
        print('Country {} has employment {}'.format(country,country_employment))


Examining country Afghanistan
Examining country Albania
Examining country Algeria
Examining country Angola
Examining country Argentina
Examining country Armenia
Examining country Australia
Examining country Austria
Examining country Azerbaijan
Examining country Bahamas
Examining country Bahrain
Examining country Bangladesh
Examining country Barbados
Examining country Belarus
Examining country Belgium
Examining country Belize
Examining country Benin
Examining country Bhutan
Examining country Bolivia
Examining country Bosnia and Herzegovina
Country Afghanistan has employment 55.70000076
Country Albania has employment 51.40000153
Country Algeria has employment 50.5
Country Angola has employment 75.69999695
Country Argentina has employment 58.40000153
Country Armenia has employment 40.09999847
Country Australia has employment 61.5
Country Austria has employment 57.09999847
Country Azerbaijan has employment 60.90000153
Country Bahamas has employment 66.59999847
Country Bahrain has employmen

In [23]:

# Numpy functions
if True:
    print(employment.mean())
    print(employment.std())
    print(employment.max())
    print(employment.sum())

def max_employment(countries, employment):
    '''
    Fill in this function to return the name of the country
    with the highest employment in the given employment
    data, and the employment in that country.
    '''
    i=employment.argmax()
    max_country = countries[i]
    max_value = employment[i]   

    return (max_country, max_value)

max_employment(countries,employment)

58.68500003850001
9.338269113687888
75.69999695
1173.70000077


('Angola', 75.69999695)

In [24]:
#vectorised operations::---a vector is a list of numbers.--same as in linear algebra--you can perform +,-,*,/,**,&,|,~,<=,>=,== etc
#multiplying by a scalar--each number get multiplied by a scalar.
# Arithmetic operations between 2 NumPy arrays
if True:
    a = np.array([1, 2, 3, 4])
    b = np.array([1, 2, 1, 2])
    print (a + b)
    print(a - b)
    print (a * b)
    print (a / b)
    print (a ** b)
    
# Arithmetic operations between a NumPy array and a single number
if True:
    a = np.array([1, 2, 3, 4])
    b = 2
    print (a + b)
    print (a - b)
    print (a * b)
    print (a / b)
    print (a ** b)

[2 4 4 6]
[0 0 2 2]
[1 4 3 8]
[1. 1. 3. 2.]
[ 1  4  3 16]
[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]


In [25]:
# Logical operations with NumPy arrays
if True:
    a = np.array([True, True, False, False])
    b = np.array([True, False, True, False])   
    print (a & b)
    print (a | b)
    print (~a)    
    print (a & True)
    print (a & False)
    print (a | True)
    print (a | False)
    

[ True False False False]
[ True  True  True False]
[False False  True  True]
[ True  True False False]
[False False False False]
[ True  True  True  True]
[ True  True False False]


In [26]:
# Comparison operations between 2 NumPy Arrays
if True:
    a = np.array([1, 2, 3, 4, 5])
    b = np.array([5, 4, 3, 2, 1])   
    print(a > b)
    print (a >= b)
    print (a < b)
    print (a <= b)
    print (a == b)
    print (a != b)

[False False False  True  True]
[False False  True  True  True]
[ True  True False False False]
[ True  True  True False False]
[False False  True False False]
[ True  True False  True  True]


In [27]:
# First 20 countries with school completion data
countries = np.array([
       'Algeria', 'Argentina', 'Armenia', 'Aruba', 'Austria','Azerbaijan',
       'Bahamas', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Bolivia',
       'Botswana', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi',
       'Cambodia', 'Cameroon', 'Cape Verde'
])

# Female school completion rate in 2007 for those 20 countries
female_completion = np.array([
    97.35583,  104.62379,  103.02998,   95.14321,  103.69019,
    98.49185,  100.88828,   95.43974,   92.11484,   91.54804,
    95.98029,   98.22902,   96.12179,  119.28105,   97.84627,
    29.07386,   38.41644,   90.70509,   51.7478 ,   95.45072
])

# Male school completion rate in 2007 for those 20 countries
male_completion = np.array([
     95.47622,  100.66476,   99.7926 ,   91.48936,  103.22096,
     97.80458,  103.81398,   88.11736,   93.55611,   87.76347,
    102.45714,   98.73953,   92.22388,  115.3892 ,   98.70502,
     37.00692,   45.39401,   91.22084,   62.42028,   90.66958
])

def overall_completion_rate(female_completion, male_completion):
    '''
    Fill in this function to return a NumPy array containing the overall
    school completion rate for each country. The arguments are NumPy
    arrays giving the female and male completion of each country in
    the same order.
    '''
    overall_rate=(female_completion+male_completion)/2
    return overall_rate
overall_completion_rate(female_completion,male_completion)

array([ 96.416025, 102.644275, 101.41129 ,  93.316285, 103.455575,
        98.148215, 102.35113 ,  91.77855 ,  92.835475,  89.655755,
        99.218715,  98.484275,  94.172835, 117.335125,  98.275645,
        33.04039 ,  41.905225,  90.962965,  57.08404 ,  93.06015 ])

In [28]:
#NUMPY INDEXING::
# Using index arrays
if True:
    a = np.array([1, 2, 3, 4])
    b = np.array([True, True, False, False])
    
    print (a[b])
    print (a[np.array([True, False, True, False])])
    
# Creating the index array using vectorized operations
if True:
    a = np.array([1, 2, 3, 2, 1])
    b = (a >= 2)
    
    print(a[b])
    print(a[a >= 2])
    
# Creating the index array using vectorized operations on another array
if True:
    a = np.array([1, 2, 3, 4, 5])
    b = np.array([1, 2, 3, 2, 1])
    
    print (b == 2)
    print (a[b == 2])

[1 2]
[1 3]
[2 3 2]
[2 3 2]
[False  True False  True False]
[2 4]


In [29]:
# Time spent in the classroom in the first week for 20 students
time_spent = np.array([12.89697233,    0.        ,   64.55043217,    0.        ,
       24.2315615 ,   39.991625  ,    0.        ,    0.        ,
      147.20683783,    0.        ,    0.        ,    0.        ,
       45.18261617,  157.60454283,  133.2434615 ,   52.85000767,
        0.        ,   54.9204785 ,   26.78142417,    0.])

# Days to cancel for 20 students
days_to_cancel = np.array([
      4,   5,  37,   3,  12,   4,  35,  38,   5,  37,   3,   3,  68, 38,  98,   2, 249,   2, 127,  35])

def mean_time_for_paid_students(time_spent, days_to_cancel):
    '''
    Fill in this function to calculate the mean time spent in the classroom
    for students who stayed enrolled at least (greater than or equal to) 7 days.
    Unlike in Lesson 1, you can assume that days_to_cancel will contain only
    integers (there are no students who have not canceled yet).
    
    The arguments are NumPy arrays. time_spent contains the amount of time spent
    in the classroom for each student, and days_to_cancel contains the number
    of days until each student cancel. The data is given in the same order
    in both arrays.
    '''
    return  time_spent[days_to_cancel>=7].mean()

mean_time_for_paid_students(time_spent,days_to_cancel)

41.05400348545454

In [30]:
#In vector operations--+= will update an existing array(in-place operation) while + will make new array and updsate it.(out-place).
#SLICE() also operates inplace--slice is just an view of a specific portion of array.

#pandas series

In [31]:
#similaritties between numpy and pandas:
#acessing,looping,functions(mean,std etc),vectorized operations
#its a cross  bwteeen list and dictionary.

In [32]:
#pandas helps us to find a row by its index:
import pandas as pd
enrollment_df.loc[0]

account_key              448
status              canceled
join_date           10-11-14
cancel_date       2015-01-14
days_to_cancel            65
is_udacity              True
is_canceled             True
Name: 0, dtype: object

In [33]:
#vectorised operation in pandas
# Addition when indexes are the same
if True:
    s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
    s2 = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
    print(s1 + s2)
    
# Indexes have same elements in a different order
if True:
    s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
    s2 = pd.Series([10, 20, 30, 40], index=['b', 'd', 'a', 'c'])
    print (s1 + s2)

# Indexes overlap, but do not have exactly the same elements
if True:
    s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
    s2 = pd.Series([10, 20, 30, 40], index=['c', 'd', 'e', 'f'])
    print (s1 + s2)

# Indexes do not overlap
if True:
    s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
    s2 = pd.Series([10, 20, 30, 40], index=['e', 'f', 'g', 'h'])
    sum=s1+s2
    print(sum)    

a    11
b    22
c    33
d    44
dtype: int64
a    31
b    12
c    43
d    24
dtype: int64
a     NaN
b     NaN
c    13.0
d    24.0
e     NaN
f     NaN
dtype: float64
a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
f   NaN
g   NaN
h   NaN
dtype: float64


In [34]:
#drop NaN values::
sum.dropna()

Series([], dtype: float64)

In [35]:
#add without NaN values::
s1.add(s2,fill_value=0)

a     1.0
b     2.0
c     3.0
d     4.0
e    10.0
f    20.0
g    30.0
h    40.0
dtype: float64

#numpy and pandas for 2D data:: 

In [36]:
#In python: it can be represented as list of list.
#In numpy: 2D array.
#In pandas : dataframe.

In [37]:
import numpy as np

# Subway ridership for 5 stations on 10 different days
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]])

# Accessing elements
if True:
    print(ridership[1, 3])
    print(ridership[1:3, 3:5])
    print(ridership[1, :])
    
# Vectorized operations on rows or columns
if True:
    print(ridership[0, :] + ridership[1, :])
    print(ridership[:, 0] + ridership[:, 1])
    
# Vectorized operations on entire arrays
if True:
    a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
    print(a + b)

2328
[[2328 2539]
 [6461 2691]]
[1478 3877 3674 2328 2539]
[1478 3877 3676 2333 2539]
[   0 5355 5701 4952 6410 5509  324    2 5223 5385]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [38]:
# NumPy axis argument
if True:
    a = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ])
    
    print(a.sum())
    print (a.sum(axis=0))  #vertical column axis
    print (a.sum(axis=1))   #row axis

45
[12 15 18]
[ 6 15 24]


In [44]:
#pandas for 2D data: dataframe::
enrollment_df.head(2)

account_key    status join_date cancel_date  days_to_cancel  is_udacity  \
0          448  canceled  10-11-14  2015-01-14            65.0        True   
1          448  canceled  05-11-14  2014-11-10             5.0        True   

   is_canceled  
0         True  
1         True

In [45]:
print(enrollment_df.mean())  #is_udacity and is_cancelled mean also calculated as pandas treat treue as 1 and false as 0.

account_key       642.775610
days_to_cancel     43.917004
is_udacity          0.010976
is_canceled         0.602439
dtype: float64


In [48]:
#taking mean of each row :
print(enrollment_df.mean(axis=1).head(2))
#taking mean of each column::
print(enrollment_df.mean(axis=0))

0    128.75
1    113.75
dtype: float64
account_key       642.775610
days_to_cancel     43.917004
is_udacity          0.010976
is_canceled         0.602439
dtype: float64


In [50]:

# DataFrame creation
if True:
    # You can create a DataFrame out of a dictionary mapping column names to values
    df_1 = pd.DataFrame({'A': [0, 1, 2], 'B': [3, 4, 5]})
    print(df_1)
# You can also use a list of lists or a 2D NumPy array
    df_2 = pd.DataFrame([[0, 1, 2], [3, 4, 5]], columns=['A', 'B', 'C'])
    print(df_2)

   A  B
0  0  3
1  1  4
2  2  5
   A  B  C
0  0  1  2
1  3  4  5


In [53]:
# Subway ridership for 5 stations on 10 different days
ridership_df = pd.DataFrame(
    data=[[   0,    0,    2,    5,    0],
          [1478, 3877, 3674, 2328, 2539],
          [1613, 4088, 3991, 6461, 2691],
          [1560, 3392, 3826, 4787, 2613],
          [1608, 4802, 3932, 4477, 2705],
          [1576, 3933, 3909, 4979, 2685],
          [  95,  229,  255,  496,  201],
          [   2,    0,    1,   27,    0],
          [1438, 3785, 3589, 4174, 2215],
          [1342, 4043, 4009, 4665, 3033]],
    index=['05-01-11', '05-02-11', '05-03-11', '05-04-11', '05-05-11',
           '05-06-11', '05-07-11', '05-08-11', '05-09-11', '05-10-11'],
    columns=['R003', 'R004', 'R005', 'R006', 'R007']
)

ridership_df

R003  R004  R005  R006  R007
05-01-11     0     0     2     5     0
05-02-11  1478  3877  3674  2328  2539
05-03-11  1613  4088  3991  6461  2691
05-04-11  1560  3392  3826  4787  2613
05-05-11  1608  4802  3932  4477  2705
05-06-11  1576  3933  3909  4979  2685
05-07-11    95   229   255   496   201
05-08-11     2     0     1    27     0
05-09-11  1438  3785  3589  4174  2215
05-10-11  1342  4043  4009  4665  3033

In [58]:
# Accessing elements
if True:
    print(ridership_df.iloc[0])
    print(ridership_df.loc['05-05-11'])
    print(ridership_df['R003'])
    print(ridership_df.iloc[1, 3])
    
# Accessing multiple rows
if True:
    print(ridership_df.iloc[1:4])

# Accessing multiple columns
if True:
    print(ridership_df[['R003', 'R005']])


R003    0
R004    0
R005    2
R006    5
R007    0
Name: 05-01-11, dtype: int64
R003    1608
R004    4802
R005    3932
R006    4477
R007    2705
Name: 05-05-11, dtype: int64
05-01-11       0
05-02-11    1478
05-03-11    1613
05-04-11    1560
05-05-11    1608
05-06-11    1576
05-07-11      95
05-08-11       2
05-09-11    1438
05-10-11    1342
Name: R003, dtype: int64
2328
          R003  R004  R005  R006  R007
05-02-11  1478  3877  3674  2328  2539
05-03-11  1613  4088  3991  6461  2691
05-04-11  1560  3392  3826  4787  2613
          R003  R005
05-01-11     0     2
05-02-11  1478  3674
05-03-11  1613  3991
05-04-11  1560  3826
05-05-11  1608  3932
05-06-11  1576  3909
05-07-11    95   255
05-08-11     2     1
05-09-11  1438  3589
05-10-11  1342  4009
