# Day1

In [1]:
#Numpy:
import numpy as np
#check numpy version:
print(np.version.version)

1.16.5


In [2]:
#calculationg mean,median and standard deviation on an array using NumPy:
numbers_array=(1,2,3,4,5)
print(np.mean(numbers_array))
print(np.median(numbers_array))
print(np.std(numbers_array))

3.0
3.0
1.4142135623730951


In [3]:
#Playing around with NumPy array ::
arr=np.array([1,2,3,4],float)
print(arr)

#You can index, slice, and manipulate a Numpy array much like you would with a Python list.
print(arr[1])
print(arr[:2])
arr[1] = 5.0
print(arr[1])
print(arr)

if True:
    array_1 = np.array([1, 2, 3], float)
    array_2 = np.array([5, 2, 6], float)
    print(array_1 + array_2)
    print(array_1 - array_2)
    print(array_1 * array_2)


[1. 2. 3. 4.]
2.0
[1. 2.]
5.0
[1. 5. 3. 4.]
[6. 4. 9.]
[-4.  0. -3.]
[ 5.  4. 18.]


In [4]:
# a 2D array/Matrix
two_D_array=np.array([[1,2,3,4],[5,6,7,8]],float)
print(two_D_array)

two_D_array[0][0]=0
print(two_D_array)
print(two_D_array[1, :])
print(two_D_array[:, 2])
print(two_D_array[:,:])

# Change False to True to see Matrix arithmetics in action
if True:
    array_1 = np.array([[1, 2], [3, 4]], float)
    array_2 = np.array([[5, 6], [7, 8]], float)
    print(array_1 + array_2)
    print(array_1 - array_2)
    print(array_1 * array_2)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
[[0. 2. 3. 4.]
 [5. 6. 7. 8.]]
[5. 6. 7. 8.]
[3. 7.]
[[0. 2. 3. 4.]
 [5. 6. 7. 8.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]


In [5]:
#In addition to the standard arthimetic operations, Numpy also has a range of other mathematical operations that you can apply
#to Numpy arrays, such as mean,median,std and dot product.
if True:
    array_1 = np.array([1, 2, 3], float)
    array_2 = np.array([[6], [7], [8]], float)
    print(array_2)
    print(np.mean(array_1))
    print(np.mean(array_2))
    print(np.dot(array_1, array_2))


[[6.]
 [7.]
 [8.]]
2.0
7.0
[44.]


# Day 2:

In [6]:
#Pandas::
import pandas as pd
#making a dataframe:
d={'Name':['Hima','mickeu'],
  'Age':[21,22],
   'Fare':pd.Series([200],index=[1]),
  'Survived':pd.Series(['yes','yes'])}
df=pd.DataFrame(d)
df

Name  Age   Fare Survived
0    Hima   21    NaN      yes
1  mickeu   22  200.0      yes

In [7]:
#Playing arounf with series::
series = pd.Series(['Dave', 'Cheng-Han', 'Udacity', 42, -1789710578])
print(series)
series = pd.Series(['Dave', 'Cheng-Han', 359, 9001],index=['Instructor', 'Curriculum Manager','Course Number', 'Power Level'])
print(series)
if True:
    cuteness = pd.Series([1, 2, 3, 4, 5], index=['Cockroach', 'Fish', 'Mini Pig',
                                                 'Puppy', 'Kitten'])
    print(cuteness > 3)
    print(cuteness[cuteness > 3])

0           Dave
1      Cheng-Han
2        Udacity
3             42
4    -1789710578
dtype: object
Instructor                 Dave
Curriculum Manager    Cheng-Han
Course Number               359
Power Level                9001
dtype: object
Cockroach    False
Fish         False
Mini Pig     False
Puppy         True
Kitten        True
dtype: bool
Puppy     4
Kitten    5
dtype: int64


In [8]:
#Pandas also has various functions that will help you understand some basicinformation about your data frame. Some of these functions are:
#1) dtypes: to get the datatype for each column
#2) describe: useful for seeing basic statistics of the dataframe's numerical  columns
#3) head: displays the first five rows of the dataset
#4) tail: displays the last five rows of the dataset
print(df.head())
print(df.dtypes)
print(df.describe)

     Name  Age   Fare Survived
0    Hima   21    NaN      yes
1  mickeu   22  200.0      yes
Name         object
Age           int64
Fare        float64
Survived     object
dtype: object
<bound method NDFrame.describe of      Name  Age   Fare Survived
0    Hima   21    NaN      yes
1  mickeu   22  200.0      yes>


In [9]:
#Example :: Create a sample Dataframe
countries = ['Russian Fed.', 'Norway', 'Canada', 'United States',
                 'Netherlands', 'Germany', 'Switzerland', 'Belarus',
                 'Austria', 'France', 'Poland', 'China', 'Korea', 
                 'Sweden', 'Czech Republic', 'Slovenia', 'Japan',
                 'Finland', 'Great Britain', 'Ukraine', 'Slovakia',
                 'Italy', 'Latvia', 'Australia', 'Croatia', 'Kazakhstan']

gold = [13, 11, 10, 9, 8, 8, 6, 5, 4, 4, 4, 3, 3, 2, 2, 2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
silver = [11, 5, 10, 7, 7, 6, 3, 0, 8, 4, 1, 4, 3, 7, 4, 2, 4, 3, 1, 0, 0, 2, 2, 2, 1, 0]
bronze = [9, 10, 5, 12, 9, 5, 2, 1, 5, 7, 1, 2, 2, 6, 2, 4, 3, 1, 2, 1, 0, 6, 2, 1, 0, 1]

d={"country_name":countries,"gold":gold,"silver":silver,"bronze":bronze}
olympic_medal_counts_df=pd.DataFrame(d)
print(olympic_medal_counts_df.head())

    country_name  gold  silver  bronze
0   Russian Fed.    13      11       9
1         Norway    11       5      10
2         Canada    10      10       5
3  United States     9       7      12
4    Netherlands     8       7       9


In [10]:
#to get columns values
print(olympic_medal_counts_df["country_name"].head(2))
print("")
print(olympic_medal_counts_df.loc[1])
print("")
print(olympic_medal_counts_df[olympic_medal_counts_df['gold']>=13])
print("")
df[["Survived","Age"]]

0    Russian Fed.
1          Norway
Name: country_name, dtype: object

country_name    Norway
gold                11
silver               5
bronze              10
Name: 1, dtype: object

   country_name  gold  silver  bronze
0  Russian Fed.    13      11       9



Survived  Age
0      yes   21
1      yes   22

In [11]:
#You can think of a DataFrame as a group of Series that share an index.This makes it easy to select 
#specific columns that you want from the DataFrame. 

#Also a couple pointers:
#1) Selecting a single column from the DataFrame will return a Series
#2) Selecting multiple columns from the DataFrame will return a DataFrame
if True:
    data = {'year': [2010, 2011, 2012, 2011, 2012, 2010, 2011, 2012],
            'team': ['Bears', 'Bears', 'Bears', 'Packers', 'Packers', 'Lions',
                     'Lions', 'Lions'],
            'wins': [11, 8, 10, 15, 11, 6, 10, 4],
            'losses': [5, 8, 6, 1, 5, 10, 6, 12]}
    football = pd.DataFrame(data)
    print(football['year'].head(2))   # shorthand for football.year
    print('')
    print(football[['year', 'wins', 'losses']].head(2))

0    2010
1    2011
Name: year, dtype: int64

   year  wins  losses
0  2010    11       5
1  2011     8       8


In [12]:
#Row selection can be done through multiple ways.
#Some of the basic and common methods are:
 #  1) Slicing
  # 2) An individual index (through the functions iloc or loc)
   #3) Boolean indexing
#You can also combine multiple selection requirements through boolean
#operators like & (and) or | (or)

if True:
    data = {'year': [2010, 2011, 2012, 2011, 2012, 2010, 2011, 2012],
            'team': ['Bears', 'Bears', 'Bears', 'Packers', 'Packers', 'Lions',
                     'Lions', 'Lions'],
            'wins': [11, 8, 10, 15, 11, 6, 10, 4],
            'losses': [5, 8, 6, 1, 5, 10, 6, 12]}
    football = pd.DataFrame(data)
    print(football.iloc[[0]])  #print(football.loc[[0]])
    print(football[3:5])
    print(football[(football.wins > 10) & (football.team == "Packers")])

   year   team  wins  losses
0  2010  Bears    11       5
   year     team  wins  losses
3  2011  Packers    15       1
4  2012  Packers    11       5
   year     team  wins  losses
3  2011  Packers    15       1
4  2012  Packers    11       5


# Day 3

In [22]:
#Pandas vectorised method:
#gives us mean of values of each columns
football_df[["wins","losses"]].apply(np.mean)

wins      9.375
losses    6.625
dtype: float64

In [25]:
#Map::
#Map takes in single value and return single value::
print(football_df["wins"].map(lambda x: x>5).head(2))

#if we want to apply it to whole dataframe::
print(football_df.applymap(lambda x: x>5).head(2))

0    True
1    True
Name: wins, dtype: bool
   wins  losses
0  True   False
1  True    True


In [32]:
#Matrix multiplication using Numpy::
a=([1,2])
b=([2,4,6],[3,5,7])
print(b)
np.dot(a,b)

([2, 4, 6], [3, 5, 7])


array([ 8, 14, 20])