In [1]:
import numpy as np
import pandas as pd

In [21]:
#create a  matrix
a = np.matrix([[1, 2], [3, 4]])  # using array of array
print('2x2 matrix is:\n', a)

[[1 2]
 [3 4]]


In [22]:
# using numpy.random.rand(row, column) to generate array of random element
c = np.matrix(np.random.rand(2,2), dtype=np.float32)
# considering the data-type as float
print(c)

[[0.783411   0.68564194]
 [0.5933236  0.09910325]]


In [23]:
#create a 3*3 matrix
A= np.arange(21,30).reshape(3,3)
print(A)

[[21 22 23]
 [24 25 26]
 [27 28 29]]


In [24]:
#take the transpose
A.transpose()

array([[21, 24, 27],
       [22, 25, 28],
       [23, 26, 29]])

In [30]:
#matrix multiplication 
A=np.arange(21,30).reshape(3,3) 
B=np.arange(31,40).reshape(3,3)
print("AB is ",A.dot(B))
print("BA is ",B.dot(A))

AB is  [[2250 2316 2382]
 [2556 2631 2706]
 [2862 2946 3030]]
BA is  [[2310 2406 2502]
 [2526 2631 2736]
 [2742 2856 2970]]


In [33]:
#find the determinant 
np.linalg.det(a)

-2.0000000000000004

In [35]:
#Code for inverse in python

#create an array arr1 
arr1 = np.arange(5,21).reshape(4,4)
#find the inverse 
np.linalg.inv(arr1)

array([[-6.77233027e+13,  6.09509724e+14, -1.01584954e+15,
         4.74063119e+14],
       [-3.26200575e+15,  3.83765382e+15,  2.11070960e+15,
        -2.68635767e+15],
       [ 6.72718140e+15, -9.50383681e+15, -1.17387058e+15,
         3.95052599e+15],
       [-3.39745235e+15,  5.05667327e+15,  7.90105198e+13,
        -1.73823144e+15]])